version: "3.6"

services:
  redis-db:
    image: redis:7.2-alpine3.18
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-net
    volumes:
      - redis-data:/data

  app:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-net
    depends_on:
      - redis-db

volumes:
  redis-data:
    driver: local

networks:
  app-net:
